### ISSUE TITLE
Unexpected mvstart in packed_real_order

### ISSUE THREAD

**Issue by zonca** [dagss/libsharp#13]
If I run this code:

```
lmax = 2
order = libsharp.packed_real_order(lmax, stride=1)  
order.mval()
order.mvstart()
```
I expect the ordering to have `m=0` first, that should be 3 elements, then `m=1` 2 elements and finally `m=2` with only `ell=2`.
So I expect `mvstart` to be: `[0, 3, 5]`

Instead I get:

```
array([0, 1, 2], dtype=int32)
array([0, 1, 3], dtype=int64)
```

Am I missing something?

**Comment by zonca** [comment]
@dagss @mreineck can you also please take a look at this?

**Comment by mreineck** [comment]
Sorry, I have no experience with the packed real storage scheme.

**Comment by dagss** [comment]
`mvstart` is a "synthetic index" which is the index in memory if l=0. Of course this element doesn't exist because if l=0 then l < m, but this is the convention for mvstart. Specifically coefficients are accessed as

```
talm[mvstart[m]+l*stride]
```

(where l is the absolute value).

See the code in sharp.c (search for mvstart).

I think you are expecting the indexing to happen as `(l-m)*stride` instead of `l*stride`?

**Comment by mreineck** [comment]
Ah ... thanks @dagss, I had completely forgotten about this trick, so I couldn't make sense of the numbers.

**Comment by mreineck** [comment]
I'm still a bit confused about the second entry ov `mvstart`:

`array([0, 1, 3], dtype=int64)`

Shouldnt the second entry be a 2 instead of a 1?

**Comment by mreineck** [comment]
Can we close this, or are there still open questions?
