### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by zonca** [dagss/libsharp#18]
Is there any plan to have a CUDA version of `libsharp`?

**Comment by mreineck** [comment]
I'm not planning to implement this - very big effort, and I don't see sufficient payback in terms of performance.

Are you asking because you are encountering any concrete bottlenecks?

**Comment by mreineck** [comment]
To be a bit more specific: libsharp SHTs reach > 100 GFlops/s on modern 4-core CPUs; it should be quite hard to beat this by much on GPUs, since we need double precision.

**Comment by nschaeff** [comment]
Hi, just to give some actual numbers: the cuda version of the SHTns spherical harmonic transform library achieves around 400+ GFlops on a K80 gpu (Kepler), and 1000+ GFlops on a P100 gpu (Pascal). These numbers were measured with lmax=1023 and include the transfer from cpu to gpu and back. If your data stays on the gpu the perf is much higher (numbers not available).

In my opinion, the gpu can achieve good performance for SHT, but it is still comparable to what you can get from current highend (e.g. SkylakeX) servers (if you include the transfer cost). If your data stays on the gpu it may be interesting.

**Comment by mreineck** [comment]
Thanks for the data points!

This is roughly in the range that I expected. Depending on one's goals, going to GPU can definitely be advantageous, if hardware and development (and maintenance) costs are dominated by other factors. For libsharp, this is not the case; the goal is to stay as minimalistic and portable as possible, without any external dependencies. GPU support is fairly vendor-specific, I think (please correct me is that has changed!), comes with a lot of dependencies, and most GPU owners will not benefit from it, because they only have consumer cards with locked double precision support.

An additional note: if the GFlop numbers you mention are measured with shtns (which I think is highly likely :), they have to be reduced by 30 or 40 percent before comparing them to libsharp numbers, because the two libraries have slightly different methodologies for measuring performance.

**Comment by mreineck** [comment]
One additional thing to consider:

For grids that have the same number of pixels in all rings, the FFT part of the SHT can be carried out fairly efficiently on GPUs. Healpix has varying pixel numbers per ring (4,8,12,16,... 4*nside), which is probably a performance nightmare for graphics hardware.

**Comment by nschaeff** [comment]
Yes, all your comments and assumption are correct.

**Comment by zonca** [comment]
thanks
