### ISSUE TITLE
Normalisation of analysis/adjoint_synthesis

### ISSUE THREAD

**Issue by Gabriel-Ducrocq** [dagss/libsharp#25]
Hello,

I am trying to use libsharp and find the following problem:
When sampling a white noise pixel map and then using adjoint_synthesis, the resulting a_lm do not have variance 1. See my code below:

`  

    nside = 2
    lmax = 2 * nside
    alm_struct = libsharp.triangular_order(lmax)
    print(alm_struct.local_size())
    order = libsharp.packed_real_order(lmax)
    grid = libsharp.healpix_grid(nside)
    list_alms = []
    list_maps = []
    for i in range(10000):
        map = np.random.normal(loc=0, scale=1, size=12*nside**2)
        list_maps.append(map)
        alm_back = libsharp.adjoint_synthesis(grid, order, map[None, None, :])
        list_alms.append(alm_back[0, 0, :])

    a1 =np.array(list_alms).T
    print("VARIANCES")
    print(np.var(np.array(list_alms), axis=0))
    print("Covariance example")
    print(np.cov(a1[[10,20], :]))
`
I get the following output:

`
VARIANCES
[3.81882475 3.75802199 3.44927839 3.46005672 3.51739053 3.81658222
 3.8200262  4.01142113 3.98576517 3.88529729 3.86343938 3.65896153
 3.81771057 3.79704237 3.92211808 3.69347394 4.09028853 3.44506011
 4.55710171 3.78255003 3.81358878 3.91577468 3.88357503 3.95017779
 3.73340248]
Covariance example
[[3.86382576 0.04520761]
 [0.04520761 3.81397017]]
`

This is surprising: since the synthesis has othonormal rows, I expect the resulting a_lm to be distributed as a standard multivariate normal. But it seems that there is a normalization constant missing.

I also note that this normalisation constant is dependent on nside (but it seems it is not on lmax), for example:

`

    nside = 4
    lmax = 2 * nside

    alm_struct = libsharp.triangular_order(lmax)
    print(alm_struct.local_size())
    order = libsharp.packed_real_order(lmax)
    grid = libsharp.healpix_grid(nside)

    list_alms = []
    list_maps = []
    for i in range(10000):
        map = np.random.normal(loc=0, scale=1, size=12*nside**2)
        list_maps.append(map)
        #alm_back = libsharp.analysis(grid, order, map[None, None, :])
        alm_back = libsharp.adjoint_synthesis(grid, order, map[None, None, :])
        list_alms.append(alm_back[0, 0, :])

    a1 =np.array(list_alms).T
    print(a1.shape)
    print("VARIANCES")
    print(np.var(np.array(list_alms), axis=0))
    print("Covariance example")
    print(np.cov(a1[[10,20], :]))`
`

Gives the following output:

`
VARIANCES
[15.34317324 15.0167094  15.07927127 15.07570511 14.90184939 14.69584301
 14.58601057 14.34606608 14.35603575 14.73322693 15.4021652  15.05573824
 15.65920864 15.25276373 15.48269064 15.08624325 15.65170701 15.23608656
 15.23706992 15.34283595 15.29359419 15.30573534 15.19867691 15.37181722
 15.25184572 15.13565876 15.66069759 15.36983521 15.78268925 15.29116691
 15.70773601 15.23845845 14.84480398 14.97435351 15.44235431 15.21879073
 16.02206478 14.19712375 16.27293992 15.41835735 15.29608637 15.56380313
 15.16174313 15.41224861 15.51884327 15.63161893 15.42497608 15.19419003
 15.02857808 15.0974164  15.45329414 15.44897246 15.16990345 15.01904046
 15.15164379 15.0892065  15.79061855 14.99200887 15.58967013 14.69410246
 15.60494403 15.60950105 15.23071353 15.09269387 15.2101855  15.44184661
 15.48837648 15.82919287 15.53281393 15.2291897  15.22795933 15.27638512
 15.54393736 14.80034968 15.7228248  15.10979903 14.82560766 15.34004596
 15.37910799 15.22486287 15.27545131]
Covariance example
[[15.40370557  0.04103769]
 [ 0.04103769 15.2951237 ]]
`

Am I missing something ?  How is it possible to normalize this transformation ?
Note also that the adjoint_synthesis function seems to induce non negligible correlations between two different components...

Thank you.

**Comment by mreineck** [comment]
I don't think that `synthesis` has orthonormal rows. As a consequence, `adjoint_synthesis` and `analysis` are different operations. Have you checked that `analysis` also doesn't do what you expect?

The normalization constant is `4*pi/(12*nside**2)`.

**Comment by mreineck** [comment]
Please also note that a spherical harmonic transform involving a Healpix grid is never exactly invertible. It is approximately invertible if the map in question is band limited at lmax \lessapprox 1.5*nside.

If you fill a map with random values, it is not band limited, and as a consequence analyzing it and then synthesizing it again will produce a quite different map.

**Comment by dagss** [comment]
As Martin says you just cannot treat spherical harmonic transforms the way you treat FFTs. You have to look at the linear algebra and what happens with the covariance matrices.

I find it very helpful myself to denote synthesis as "Y" and analysis as "Y^T W".

See for instance section 4.5 in https://arxiv.org/pdf/1308.5299, section 3.2 in https://arxiv.org/abs/1710.00621

**Comment by dagss** [comment]
In your example, when you do "analysis", you expect the covariance matrix `Y^T W W Y`.

When you do adjoint synthesis, you expect the covariance matrix `Y^T Y`.

If you changed normalization you could make it so that for some of these get `Y^T W^{1/2} W^{1/2} Y`. This is *approximately* the identity matrix, and how close it is *depends on grid and resolution parameters*.

To implement this you can simply adjust the "ring weights" passed to libsharp (take the square root). This again is just a utility for scaling each pixel with a weight (note that whatever you do, the scaling should always happen in pixel domain, regardless of direction of transform, as weights are different for different pixels.)

I haven't verified this myself but it "should" work. You are then defining your own convention here.

I guess it is a bit similar to how in FFTs you can have 1/n or 1/sqrt(n) and so on, but it is a bit messier because a) the normalization constant is different for different pixels, and b) you don't get the identity matrix, just an approximation.

**Comment by Gabriel-Ducrocq** [comment]
Thanks for your quick answers !

> I don't think that synthesis has orthonormal rows

Sorry I meant orthonormal columns: I expected `Y` to have orthonormal columns. From what you are saying, I understand this is not the case and will only be true for a transformation `W^{1/2}Y`, depending on grid and parameters resolution.

This surprises me a lot, in the following paper:
https://arxiv.org/pdf/astro-ph/0407028.pdf
The authors claim the systems (24) and (25), section 3.1, to be diagonal in the case of a uniform noise and no galactic cut. It made sense to me in the case Y had orthonormal columns, but if it is not the case, how can this system be diagonal ?

**Comment by hke** [comment]
Hi Gabriel,

It's worth noting that the linear system in Eq 24 is general valid, independent of basis. In the case of uniform noise and no mask, invN may therefore be described directly in harmonic space without reference to pixels at all. In that case the system *is* exactly diagonal. 

However, it is definitely true that whenever SHTs are involved, nothing is mathematically diagonal anymore, and in particularly not with the HEALpix grid. 

In practice, though, these numerical issues can usually be controlled quite well by judicious choices of lmax, Nside and smoothing scale.

Hans Kristian



20. des. 2019, 13:16 kl. 13:16 skrev Gabriel Ducrocq <notifications@github.com>:

**Comment by Gabriel-Ducrocq** [comment]
Hi Hans, 

Thanks for your answer, it clarifies a lot of things.

> In the case of uniform noise and no mask, invN may therefore be described directly in harmonic space without reference to pixels at all

Could you elaborate on this or point me to references regarding that ?

Thank you,

Gabriel.

**Comment by dagss** [comment]
I review it in Section 3.5.3 in my M.Sc. thesis

https://www.duo.uio.no/handle/10852/10849


man. 23. des. 2019, 11:08 skrev Gabriel Ducrocq <notifications@github.com>:

**Comment by dagss** [comment]
Seems that website went down between yesterday and today. But someone
copied it here:

https://www.semanticscholar.org/paper/Hemispherical-Power-Asymmetry-in-the-Cosmic-by-Seljebotn/2d1d3ff48d214d969a0c8783aa198f47cfea602d


man. 23. des. 2019, 20:45 skrev Dag Sverre Seljebotn <dagseljebotn@gmail.com

**Comment by dagss** [comment]
...and note that if RMS is constant, then the expansion of RMS into
spherical harmonics then only the monopole coeficcient is nonzero.

Reading it again that was a complex way to find what you are asking. In
general for inverse noise matrix Hans Kristian is talking out, if it is D
in pixel domain then in SH it is

 Y^T D Y

or what you are computing, if covariance in pixel domain is  D then in
spherical harmonic domain it is

Y^T W D W Y

Then if D is constant in all pixels you can pull it out of the product.
And, W is closely approximated by a scalar (4 pi/npix) at least for high
resolutions. So I tend to just pull out scalar factors so that you are left
with

(Some scalars in front, D W^-1 or D W , depending on context) * Y^T W Y

And then note (if resolution parameters are set correctly) that Y^T W Y = 1.


man. 23. des. 2019, 20:45 skrev Dag Sverre Seljebotn <dagseljebotn@gmail.com

**Comment by dagss** [comment]
Those algebraic properties of SHTs are reviewed in papers already linked to ... and if not there, search up my paper on Wavemoth and the papers referenced therein by Tygert; and they should I believe cover the orthogonality properties of SHTs (if it was not done in the libsharp paper)

**Comment by Gabriel-Ducrocq** [comment]
Hi, 

Thank you for your answers and for your master thesis, it helps and clarifies a lot !
I will close the issue since I have no more questions regarding that topic.

Thanks again,
Gabriel.
