### ISSUE TITLE
Harmonic decomposition of spin 2 fields

### ISSUE THREAD

**Issue by alecarones** [dagss/libsharp#26]
Hi,

I am interested in harmonic decomposition of spin 2 fields (such as the combination Q+iU of Stokes parameters of microwave maps).

According to what I have seen, the function libsharp.analysis of the python wrapper outputs the E and B-modes harmonic coefficients when the Q and U maps are given as an input. Am i wrong?

If this is the case, is there a way to obtain directly the spin 2 harmonic coefficients through the libsharp python wrapper?

Thank you

**Comment by mreineck** [comment]
> According to what I have seen, the function libsharp.analysis of the python wrapper outputs the E and B-modes harmonic coefficients when the Q and U maps are given as an input. Am i wrong?

I have not written the Python wrapper myself, but I'm pretty sure that's correct.
Same for the other direction: you provide E and B coefficients and get maps for Q and U.

Working directly with spin- (+2/-2) quantities is not implemented in `libsharp` at the moment, for two reasons:
- in the astronomical context, people typically don't need this (as far as I know :)
- contrary to intuition, transforming Q+iU into spin-(+2) coefficients is about as expensive as doing both spin +2 and spin -2 transforms on Q+iU and Q-iU, respectively, so there is not really much time to be gained by providing this functionality. Also the internal format for spherical harmonic coefficients used by `libsharp` cannot really accommodate coefficients of pure spin +2 or spin -2, because they don;t exhibit the nice symmetries of the E and B coefficients.

So I'd suggest to do the E/B->spin +2/-2 conversion as a pre- or post-processing step. Efficiency-wise this is not a noticeable loss.

**Comment by alecarones** [comment]
Thank you for your response,

Therefore the E and B coefficients are computed from Q and U maps through eq. 4 in https://arxiv.org/pdf/astro-ph/9709271.pdf?

**Comment by mreineck** [comment]
I think so, perhaps with the exception of a factor (-1) somewhere. The exact definition of what's happening is given in section 2.4 of https://arxiv.org/abs/1010.2084.

Sorry, don't have time at the moment to double-check...

**Comment by alecarones** [comment]
I see. 
Thank you very much.
